name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: false
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Run module build
        run: npm run module:build
